version: '3.8'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_CLUSTER_NAME: ${ELASTIC_CLUSTER_NAME}
      ELASTIC_NODE_NAME: ${ELASTIC_NODE_NAME}
      ELASTIC_INIT_MASTER_NODE: ${ELASTIC_INIT_MASTER_NODE}
      ELASTIC_DISCOVERY_SEEDS: ${ELASTIC_DISCOVERY_SEEDS}
      ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
      bootstrap.memory_lock: 'true'
      TZ: ${TZ}
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./secrets/elastic-certificates.p12/:/usr/share/elasticsearch/config/certs/elastic-certificates.p12
      - ${SSLCERT}:/usr/share/elasticsearch/config/hexactacom.crt
      - ${SSLKEY}:/usr/share/elasticsearch/config/hexactacom.key
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${SSLCERT}:/usr/share/elasticsearch/config/hexactacom.crt
      - ${SSLKEY}:/usr/share/elasticsearch/config/hexactacom.key
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: '[${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}]'
      TZ: ${TZ}
    ports:
      - 5601:5601

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    depends_on:
      - kibana
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${SSLCERT}:/etc/ssl/certs/file.crt
      - ${SSLKEY}:/etc/ssl/private/file.key
    restart: unless-stopped
    environment:
        TZ: ${TZ}

